### ISSUE TITLE
Unable to define word(s)

### ISSUE THREAD

**Issue by oguya** [urbanslug/zipper-bot#2]
The bot's is unable to define to a word

**steps to reproduce**
- On IRC, define a sample word `exam`:

        @define exam

- the bot's throws a stacktrace, probably because it can't find the function `count` in `define.rb`

        [2015/04/13 12:53:43.249] !! [Thread done] For #<Cinch::Handler @event=:channel pattern=#<Cinch::Pattern:0x00000002421588 @prefix=nil, @pattern=//, @suffix=nil>>: #<Thread:0x00000002545748> -- 0 remaining.
        [2015/04/13 12:53:43.799] !! /home/james/src/zipper-bot/define.rb:20:in `execute': undefined local variable or method `count' for #<Define:0x0000000241f918> (NameError)
        [2015/04/13 12:53:43.799] !!    /home/james/.gem/ruby/gems/cinch-2.2.4/lib/cinch/plugin.rb:419:in `call'
        [2015/04/13 12:53:43.799] !!    /home/james/.gem/ruby/gems/cinch-2.2.4/lib/cinch/plugin.rb:419:in `block (2 levels) in __register_matchers'
        [2015/04/13 12:53:43.799] !!    /home/james/.gem/ruby/gems/cinch-2.2.4/lib/cinch/handler.rb:99:in `call'
        [2015/04/13 12:53:43.799] !!    /home/james/.gem/ruby/gems/cinch-2.2.4/lib/cinch/handler.rb:99:in `block in call'
        [2015/04/13 12:53:43.799] !! [Thread done] For #<Cinch::Handler @event=:message pattern=#<Cinch::Pattern:0x0000000241f878 @prefix=/^@/, @pattern=/define\ ?(.*)/, @suffix=nil>>: #<Thread:0x0000000253d430> -- 0 remaining.

**Comment by urbanslug** [comment]
Is this issue satisfactorily handled?

**Comment by oguya** [comment]
yes! :+1:  teh bot returns definitions of most words.
