### ISSUE TITLE
No results from NP(Now Playing)

### ISSUE THREAD

**Issue by oguya** [urbanslug/zipper-bot#7]
- On IRC:

        14:46 < R0ok_> @np

- heroku logs for the bot

        $ heroku logs --tail
        ...
        2015-09-08T11:46:31.649853+00:00 app[bot.1]: [2015/09/08 11:46:31.649] !! /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/open-uri.rb:353:in `open_http': 504 Gateway Time-out (OpenURI::HTTPError)
        2015-09-08T11:46:31.649922+00:00 app[bot.1]: [2015/09/08 11:46:31.649] !!       /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/open-uri.rb:709:in `buffer_open'
        2015-09-08T11:46:31.649960+00:00 app[bot.1]: [2015/09/08 11:46:31.649] !!       /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
        2015-09-08T11:46:31.650008+00:00 app[bot.1]: [2015/09/08 11:46:31.649] !!       /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
        2015-09-08T11:46:31.650057+00:00 app[bot.1]: [2015/09/08 11:46:31.650] !!       /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
        2015-09-08T11:46:31.650096+00:00 app[bot.1]: [2015/09/08 11:46:31.650] !!       /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
        2015-09-08T11:46:31.650135+00:00 app[bot.1]: [2015/09/08 11:46:31.650] !!       /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/open-uri.rb:689:in `open'
        2015-09-08T11:46:31.650175+00:00 app[bot.1]: [2015/09/08 11:46:31.650] !!       /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/open-uri.rb:34:in `open'
        2015-09-08T11:46:31.650212+00:00 app[bot.1]: [2015/09/08 11:46:31.650] !!       /app/np.rb:19:in `execute'
        2015-09-08T11:46:31.650249+00:00 app[bot.1]: [2015/09/08 11:46:31.650] !!       /app/vendor/bundle/ruby/2.0.0/gems/cinch-2.2.4/lib/cinch/plugin.rb:419:in `call'
        2015-09-08T11:46:31.650332+00:00 app[bot.1]: [2015/09/08 11:46:31.650] !!       /app/vendor/bundle/ruby/2.0.0/gems/cinch-2.2.4/lib/cinch/plugin.rb:419:in `block (2 levels) in __register_matchers'
        2015-09-08T11:46:31.650362+00:00 app[bot.1]: [2015/09/08 11:46:31.650] !!       /app/vendor/bundle/ruby/2.0.0/gems/cinch-2.2.4/lib/cinch/handler.rb:99:in `call'
        2015-09-08T11:46:31.650401+00:00 app[bot.1]: [2015/09/08 11:46:31.650] !!       /app/vendor/bundle/ruby/2.0.0/gems/cinch-2.2.4/lib/cinch/handler.rb:99:in `block in call'
        2015-09-08T11:46:31.650515+00:00 app[bot.1]: [2015/09/08 11:46:31.650] !! [Thread done] For #<Cinch::Handler @event=:message pattern=#<Cinch::Pattern:0x007f2e7d1c5b08 @prefix=/^@/, @pattern=/np\ ?(.*)/, @suffix=nil>>: #<Thread:0x007f2e7d15e3b8> -- 0 remaining.

**Comment by urbanslug** [comment]
No, lastfm changed everything man. Have you looked at their site? We'll have to update it to work with the new API.
